version: '3.8'

services:
  web:
    image: honeyjack/mini-erp:latest
    ports:
      - "8800:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
