name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: honeyjack/mini-erp

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests with Docker Compose
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Compose services
      run: |
        docker compose build

    - name: Start services and wait for readiness
      run: |
        docker compose up -d
        # Wait for PostgreSQL to be ready
        timeout 60 bash -c 'until docker compose exec -T db pg_isready -U postgres; do sleep 2; done'
        # Wait for Django to be ready
        timeout 60 bash -c 'until docker compose exec -T web python manage.py check; do sleep 2; done'

    - name: Run database migrations
      run: |
        docker compose exec -T web python manage.py migrate

    - name: Run unit tests
      run: |
        docker compose exec -T web python manage.py test users inventory sales purchases reports --keepdb --verbosity=2

    - name: Run E2E tests
      run: |
        docker compose exec -T web python manage.py test tests_e2e --keepdb --verbosity=2

    - name: Run business flow E2E test
      run: |
        docker compose exec -T web python manage.py test tests_e2e.test_business_flow.BusinessFlowE2ETest.test_complete_business_flow --keepdb --verbosity=2

    - name: Cleanup services
      if: always()
      run: |
        docker compose down

  auto-tag:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    name: Auto Generate Tag
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Generate new tag
      id: generate_tag
      run: |
        python scripts_utils/generate_tag.py --type patch --no-push --message "Auto-generated tag from CI/CD pipeline"
        NEW_TAG=$(git describe --tags --abbrev=0)
        echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $NEW_TAG"

    - name: Push tag to repository
      run: |
        git push origin ${{ steps.generate_tag.outputs.tag }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, auto-tag]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: read
      packages: write
    name: Build and Push to Docker Hub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Notify success
      run: |
        echo "✅ Build and push completed successfully!"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        echo "Tags: ${{ steps.meta.outputs.tags }}"
